### ISSUE TITLE
default host_statuses should include Maintenance as well

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-ansible-cluster-upgrade#25]
it's the desired state, and people may prefer to move "risky" hosts manually beforehand, so please include it as a valid state.
No other state would be suitable, AFAICT

**Comment by machacekondra** [comment]
It's a valid state, but not default state. So do you suggest to have as a default state `up` and `maintenance` or only `maintenance`?

**Comment by mwperina** [comment]
On the other hand you may have hosts in maintenance, which for example require hardware maintenance and you definitely don't want to execute upgrade on them. If administrator would like to execute upgrade on hosts in maintenance, he could allow that in `host_statuses` role option (or he could even specify host by names).
Anyway I think the default values are correct and if administrators need some extra host handling, role has enough ways how to support them.
