### ISSUE TITLE
stop_pinned_to_host_vms should be renamed

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-ansible-cluster-upgrade#26]
We shouldn't call non migrateable VMs "pinned". They are not necessarily pinned and we also support migration for pinned VMs in 4.3. The option is called Migration Mode: "Do not allow migration", that's the one that matters. Should be clear in documentation too (and code, if it doesn't behave that way;)

**Comment by machacekondra** [comment]
The variable is called `stop_non_migratable_vms` the alias for it is `stop_pinned_to_host_vms` to keep backward compatibility as it used to be called like that. I will describe that in doc to be clear.
