### ISSUE TITLE
pinned VMs are not "!migrateable"

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-ansible-cluster-upgrade#32]
https://github.com/oVirt/ovirt-ansible-cluster-upgrade/blob/73165349674df3666bc7805dffde3650f0a89d19/tasks/pinned_vms.yml#L8

With https://gerrit.ovirt.org/#/c/94316/ manually migrateable VMs are migrated on move to maintenance as well. They should not be shut down here.

**Comment by machacekondra** [comment]
Nice, we need to add check what's the backend version and still do manual shutdown in case of 4.2.
