### ISSUE TITLE
handle the hosted-engine cluster as a special case

### ISSUE THREAD

**Issue by tiraboschi** [oVirt/ovirt-ansible-cluster-upgrade#40]
Currently the cluster upgrade could fail if on hosted-engine because we are not able to set all the cluster hosts into maintenance mode at the same time since at least one host has to run the engine VM.

A manual workaround procedure is:
- set HE global maintenance mode
- set one of the hosted-engine hosts into maintenance mode
- move it to a different temporary cluster
- shutdown the engine VM
- manually restart the engine VM on the host on the temporary cluster directly executing on that host: 'hosted-engine --vm-start'
- connect again to the engine
- set all the hosts of the initial cluster into maintenance mode
- upgrade the cluster
- shut down again the engine VM
- manually restart the engine VM on one of the hosts of the initial cluster
- move back the host that got into a temporary cluster to its initial cluster

We can automate this as well.

**Comment by mwperina** [comment]
AFAIK we are not putting all hosts in the cluster into Maintenance at once, but we are doing upgrades one host after another using:

1. Select host from list of hosts
2. Put host to Maintenace
3. Upgrade the hosts
4. Activate the host
5. If steps 2.-4. are successful continue with the next host

With that approach HE VM should be migrated automatically to different host, so what are the benefits to implement above scenario comparing to the current one?

**Comment by tiraboschi** [comment]
> With that approach HE VM should be migrated automatically to different host, so what are the benefits to implement above scenario comparing to the current one?

It comes from the report of an upstream user in a thread names "[ovirt-users] Changing CPU type from Opteron G3 to Epyc with hosted engine in 4.3".
Tracked in a bug here:
https://bugzilla.redhat.com/1672859

Normally setting HE global maintenance mode, upgrading hosts, the engine VM and than raising the cluster compatibility level at the end (and eventually rebooting all the cluster VMs including the HE one to consume the feature of the new cluster) is enough.

In that specific case he was using using AMD Epyc hosts that where consumed as Opteron G3 in 4.2 but while now we have to use the new CPU type.
But in this specific case the cluster upgrade is failing with "Error while executing action: Cannot change Cluster CPU type unless all Hosts attached to this Cluster are in Maintenance".

The same issue will probably happen also for:
Intel Conroe Family
Intel Penryn
AMD Opteron G1/G2/G3
that are not there anymore in 4.3.

This is not hosted-engine specific although the hosted-engine case requires a special treatment.

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
